import type { Metadata } from "next";
import { Inter, Montserrat, Urbanist } from "next/font/google";
import localFont from "next/font/local";
import React from "react";
import "./globals.css";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const urbanist = Urbanist({ subsets: ["latin"], variable: "--font-urbanist" });
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const materialSymbols = localFont({
  variable: "--font-family-symbols", // Variable name (to reference after in CSS/styles)
  style: "normal",
  src: "../node_modules/material-symbols/material-symbols-rounded.woff2", // This is a reference to woff2 file from NPM package "material-symbols"
  display: "block",
  weight: "100 700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${materialSymbols.variable}`} lang="en">
      <body
        className={`${inter.variable} ${urbanist.variable} ${montserrat.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
